### ISSUE TITLE
Current version can't be installed with composer on TYPO3 9

### ISSUE THREAD

**Issue by sypets** [ervaude/fluid_styled_slider#6]
because of dependency in composer.json

`"typo3/cms-core": "^7.6.0 || ^8.7.0"`

Do you want to create a dedicated 9 version?

**Comment by ervaude** [comment]
Hi @sypets 
this is ment to be an example and not so much an extension that you should install in your projects :)

If I find the time, I'll look into updating it for 9LTS but it has somewhat low priority for me.

**Comment by sypets** [comment]
@ervaude Thank you for the clarification.

I realize it is an example and not something that is meant for production.

But, it is recommended to install it in the docs. See [Code examples](https://docs.typo3.org/typo3cms/CoreApiReference/Introduction/Index.html#code-examples)

> Quite a few others come from the "styleguide" extension. You can install it, if you want to try out these examples yourself and use them as a basis for your own extensions.

I think it might be helpful for developers. Of course, people could just look in the code. But the combination of installing this extension, creating the sample content elements, looking at them and comparing to the code is something that might be helpful for developers. I think that is why it has been pointed out in the documentation.

It used to be just installable so I am not really sure how to proceed. We can remove the reference from the docs (there are several more places) or add a hint or just leave it the way it is.

**Comment by ervaude** [comment]
I just released a cleaned up version 2.0.0 that is compatible with TYPO3 9LTS.

Support for 7LTS was dropped, though.
